In [6]:
import numpy as np

In [5]:
pip install numpy

                                              0.0/15.8 MB ? eta -:--:--
                                              0.0/15.8 MB ? eta -:--:--
                                              0.0/15.8 MB ? eta -:--:--
                                              0.1/15.8 MB 1.1 MB/s eta 0:00:15
                                             0.2/15.8 MB 985.7 kB/s eta 0:00:16
                                             0.2/15.8 MB 985.7 kB/s eta 0:00:16
                                             0.2/15.8 MB 985.7 kB/s eta 0:00:16
                                             0.3/15.8 MB 827.5 kB/s eta 0:00:19
                                             0.3/15.8 MB 827.5 kB/s eta 0:00:19
                                             0.3/15.8 MB 838.1 kB/s eta 0:00:19
                                             0.3/15.8 MB 838.1 kB/s eta 0:00:19
                                             0.3/15.8 MB 838.1 kB/s eta 0:00:19
                                             0.3/15.8 MB 838.1 kB

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# creating the numpy array

arr1 = np.array([[1,2],[3,4]])

# dtype in array
arr2 = np.array([1,2,3,4], dtype='f')


print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[1. 2. 3. 4.]


In [10]:
# indexing in numpy array

print(arr1[0])

print(arr[-4])

[1 2]
2


In [15]:
# string type array in numpy

mystr = np.array(['a','b','c','d'], dtype=np.str_)
print(mystr)

['a' 'b' 'c' 'd']
