In [6]:
import numpy as np

a = np.array([1,3,2,4,5,6,7,8,9])
print(a)

[1 3 2 4 5 6 7 8 9]


In [13]:
# reshaping array
print(a.reshape(3,3))

# elementwise operation on array
a1 = np.array([1,2,4,5,6])
a2 = np.array([0,9,8,7,3])
print(a1+a2)

print(a1-a2)

print(a2*a1)

print(a2/a1)

print(a2%a1)

[[1 3 2]
 [4 5 6]
 [7 8 9]]
[ 1 11 12 12  9]
[ 1 -7 -4 -2  3]
[ 0 18 32 35 18]
[0.  4.5 2.  1.4 0.5]
[0 1 0 2 3]


In [17]:
# Aggregate Operations in array
ar = np.array([2,4,6,8,10])

print(ar.sum())

print(ar.min())

print(ar.max())

print(ar.mean())

print(ar.std())

30
2
10
6.0
2.8284271247461903


In [23]:
# array indexing and slicing
arr = np.array([1,3,5,7,9,11,13])

# call element with index 
print(arr[3])

# slicing 
print(arr[:5])
# or
print(arr[3:])
# or
print(arr[2:5])

7
[1 3 5 7 9]
[ 7  9 11 13]
[5 7 9]


In [33]:
# insert Row/Columns in array -> np.insert(array_name, index, values)
print(np.insert(arr,1,5))

# Append Row/Columns in array 
arr1 = np.array([[1,2],[3,4],[5,6]])
print(np.append(arr1,[[7,8]],axis=0))

# Numpy Linespace
print(np.linspace(1,20, 6))

# numpy eye
print(np.eye(5))


[ 1  5  3  5  7  9 11 13]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[ 1.   4.8  8.6 12.4 16.2 20. ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
# numpy unique 
arr2 = np.array([1,3,4,5,3,4,6,8,9,12])
print(np.unique(arr2))

# numpy sort 
print(np.sort(arr2))

# numpy full 
print(np.full((3,4),7))

[ 1  3  4  5  6  8  9 12]
[ 1  3  3  4  4  5  6  8  9 12]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
